trigger:
  branches:
    include:
      - main
      - uat
      - dev

variables:
  - name: ENV
    value: $[replace(variables['Build.SourceBranchName'], 'main', 'prd')]
  - name: ENV
    value: $[replace(variables['ENV'], 'uat', 'uat')]
  - name: ENV
    value: $[replace(variables['ENV'], 'dev', 'dev')]

stages:
  - stage: Deploy
    jobs:
      - job: DeployNotebook
        steps:
          - template: templates/deploy-job.yml
            parameters:
              env: $(ENV)
